<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Social Networking</title>

<link type="text/css" rel="stylesheet" rev="stylesheet" href="/.php_files/styles.css" />

</head>

<body>

<div id="page">
    
	<div id="header">
		<div class="top">
			<div class="inside">
					<a href=""><img src="/.php_files/images/header_title.gif" width="270" height="51" alt="my personal network" /></a>
			</div>
		</div>
		<div class="bot">
			<div class="inside">
			</div>
		</div>
	</div><!-- /header -->
        
    
	<div id="content">
	
